---
title: "Modul Basis Data"
author: "Kinanthi Trah Asmaraningtyas & Dinda Dwi Anugrah Pertiwi"
output: html_document
---

# BAB I BASIS DATA

## Pengenalan Basis Data

::: {style="text-align: justify;"}
Basis data adalah kumpulan data yang saling berhubungan secara logis dan didesain untuk mendapatkan data yang dibutuhkan oleh suatu organisasi (Indrajani, 2015).

Basis data (database) adalah sebuah kumpulan informasi yang disimpan di dalam komputer dan dapat diperiksa, diolah, atau dimanipulasi secara sistematis menggunakan program komputer. Istilah ***“basis”*** mengacu pada gudang atau tempat penyimpanan, sedangkan ***“data”*** merujuk pada fakta-fakta yang dikumpulkan. Dengan menggunakan basis data, pengguna dapat menyimpan informasi dalam media lain dan mengaksesnya kembali ketika diperlukan.
:::

## Komponen Basis Data

Komponen-komponen dari basis data terdiri dari:

::: {style="text-align: justify;"}
1.  **Perangkat keras *(Hardware***) **:** Merupakan komponen fisik yang terdiri dari komputer, server, penyimpanan data, dan perangkat keras lainnya yang digunakan untuk menyimpan dan mengakses basis data.

2.  **Sistem Operasi *(Operating System)*** **:** Merupakan perangkat lunak yang mengelola sumber daya perangkat keras dan menyediakan lingkungan yang diperlukan untuk menjalankan basis data.

3.  **Basis Data**a ***(Database)*** **:** Merupakan kumpulan data yang tersimpan di dalam komputer dan terorganisir dalam suatu struktur tertentu, seperti tabel, relasi, atau objek, untuk memudahkan pengaksesan dan pengelolaan data.

4.  **Sistem Manajemen Basis Data (DBMS):** Merupakan perangkat lunak yang digunakan untuk mengelola, mengatur, dan mengontrol basis data. DBMS menyediakan antarmuka yang memungkinkan pengguna untuk berinteraksi dengan basis data, melakukan operasi seperti penyimpanan, pengambilan, pembaruan, dan penghapusan data.

5.  **Pengguna *(User)*:** Merupakan individu atau entitas yang menggunakan basis data. Pengguna dapat memiliki peran yang berbeda, seperti pengguna akhir yang menggunakan aplikasi untuk mengakses dan memanipulasi data, atau administrator basis data yang bertanggung jawab untuk mengatur dan mengelola basis data.

6.  **Aplikasi:** Merupakan perangkat lunak lain yang digunakan bersama dengan basis data untuk menyediakan fungsionalitas tambahan. Aplikasi ini dapat berupa program khusus yang dibangun untuk keperluan tertentu atau aplikasi umum yang menggunakan basis data sebagai sumber data mereka.
:::

# BAB 3 DBMS

## Pengenalan DBMS

::: {style="text-align: justify;"}
Database Management System (DBMS) DBMS adalah perangkat lunak yang memungkinkan pemakai untuk mendefinisikan, mengelola, dan mengontrol akses ke basis data. DBMS yang mengelola basis data relational disebut dengan Relational DBMS (RDBMS).Contoh perangkat lunak yang termasuk DBMS: dBase, FoxBase, Rbase, Microsoft-Access, Borland Paradox / Borland Interbase, MS-SQL Server, Oracle, Informix, Sybase, MySQL, dll.
:::

## Bahasa dalam DBMS

::: {style="text-align: justify;"}
**Structure Query Language (SQL)** adalah bahasa standar basis data yang digunakan aplikasi atau pemakai untuk berinteraksi dengan basis data melalui DBMS.

SQL dibagi menjadi dua, yaitu:

1.  ***Data Definision Language*** ***(DDL)***

    SQL yang digunakan untuk mendefinisikan skema di database, seperti untuk membuat, memodifikasi, serta menghapus struktur database.

2.  ***Data Manipulation Language*** ***(DML)***

    SQL yang digunakan untuk mengkases dan mengelola data pada basis data.
:::

## Komponen DBMS

::: {style="text-align: justify;"}
Menurut Connolly dan Begg (2010:68-71), ada 5 komponen utama dari lingkungan DBMS: Hardware, Software, Data, Prosedur, dan People.

1.  **Hardware**

    DBMS dan aplikasinya memerlukan perangkat keras untuk dapat dijalankan.Perangkatkeras dapat terdiri dari single personal computer, single mainframe, atau sebuah jaringan computer.

2.  **Software**

    Komponen perangkat lunak terdiri dari perangkat lunak DBMS dan program aplikasidengan sistem operasi, didalamnya terdapat perangkat lunak jaringan apabila DBMSmembutuhkan sebuah jaringan untuk digunakan. Pada umumnya program aplikasi ditulisdalam bahasa pemrograman generasi ketiga (3GL) seperti ‘C’, C++, Java, Visual Basic,COBOL, Fortran, Pascal, atau bahasa pemrograman generasi keempat (4GL), sepertiSQL, yang juga terdapat pada bahasa pemrograman generasi ketiga.

3.  **Data**

    Data merupakan komponen penting dalam sebuah DBMS, terutama dari sudutpandang pengguna akhir. Data menghubungkan komponen mesin (Hardware) dengan manusia

4.  **Prosedur**

    Prosedur mengarah pada instruksi dan peraturan yang mengatur rancangan danpenggunaan dari basis data. Ini seperti mencakup instruksi-instruksi, yaitu:

    -   Log on ke DBMS.

    -   Menggunakan fasilitas DBMS program aplikasi tertentu.

    -   Memulai dan mengakhiri DBMS.

    -   Membuat duplikat back-up basis data.

    -   Menangani kerusakan perangkat keras atau perangkat lunak.

    -   Mengubah struktur table, mengatur ulang data antara banyak disk, meningkatkan kinerja atau penyimpanan arsip pada secondary storage

5.  **People**

    People merupakan komponen terakhir yang terlibat dengan sistem.Berikut terdapat beberapa tiperole atau peran yang terlibat dalam sebuah DBMS, yaitu :

    1.  Data dan database administratorsa.
        -   Data Administrator (DA) bertanggung jawab dalam mengatur sumber data, meliputiperencanaan basis data, standar pengaturan dan pengembangan, kebijakan danprosedur maupun rancangan konseptual dan logika basis data.

        -   Database Administrator (DBA) bertanggung jawab dalam realisasi fisik basis datameliputi rancangan physicalbasis data dan implementasi, keamanan, dan pengaturanintegritas, menjaga sistem operasional dan memastikan kinerja aplikasi untukkepuasan pengguna.
:::

## Kelebihan DBMS

-   Mengurangi pengulangan data

-   Mencapai independensi data

-   Mengintegrasikan data beberapa file

-   Mengambil data dan informasi dengan cepat

-   Meningkatkan keamanan

## Kekurangan DBMS:

::: {style="text-align: justify;"}
Menurut Conolly dan begg (2010:80-81), Database Management System (DBMS) memiliki kekurangan, berikut ini merupakan kekurangan DBMS antara lain :

a\. Kompleks

DBMS merupakan bagian dari perangkat lunak yang sangat kompleks.Kesalahan terhadap pengertian sistemakan megakibatkan rancangan keputusan yang buruk padasuatu organisasi sehingga perancang basis data dan pengembang basis data, databaseadministrator (DBA) serta end-userperlu mengerti tentang keuntungan fungsional DBMS terlebih dahulu.

b\. Ukuran

Kompleksitas dan banyaknya kegunaan dari DBMS menjadikannya sebagaiperangkat lunak yang sangat besar, sehingga memerlukan tempat penyimpanan datayang besar dan juga membutuhkan memori yang cukup agar bisa berjalan secaraefisien.

c\. Biaya

Biaya yang dikeluarkan untuk DBMS sangat bervariasi, tergantung dari lingkungandan kegunaan yang disediakan oleh DBMS tersebut.

d\. Biaya tambahan untuk perangkat keras

Kebutuhan tempat penyimpanan data untuk DBMS dan basis data mungkinmengharuskan pembelian tempat khusus penyimpanan data tambahan.

e\. Biaya Konversi

Dalam situasi tertentu, biaya untk DBMS dan perangkat keras tambahan dapatmenjadi penting dibanng dengan biaya konversi dari aplikasi yang sudah ada agar dapatberjalan di DBMS dan perangkat keras baru.

f\. Performa

g\. Kemungkinan gagal yang tinggi

Pemusatan dari sumber daya meningkatkan kerentanan sistemyang disebabkan olehsemua pemakai dan aplikasi bergantung pada ketersediaan dari DBMS, kegagalan darisalah satu komponen dapat membuat operasi terhent
:::
